name: Undeploy
on:
  workflow_dispatch
permissions:
  id-token: write
  contents: read
jobs:
  undeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/aws-github-role
          role-session-name: aws-github-role
          aws-region: ${{ vars.AWS_REGION }}
      - name: Terraform cache
        uses: actions/cache@v3
        with:
          path: iac/.terraform
          key: ${{ runner.os }}-terraform
      - name:  Terraform Init & Destroy
        run: |
          cd iac
          terraform init -reconfigure -backend-config=env/dev.hcl
          terraform destroy -target=module.lambda -var-file=env/dev.tfvars -var="region=${{ vars.AWS_REGION }}" -var="bucket_prefix=${{ vars.BUCKET_PREFIX }}" -var="repository=${{ vars.REPOSITORY }}" -auto-approve
          terraform destroy -target=module.buckets -var-file=env/dev.tfvars -var="region=${{ vars.AWS_REGION }}" -var="bucket_prefix=${{ vars.BUCKET_PREFIX }}" -var="repository=${{ vars.REPOSITORY }}" -auto-approve
